module.exports = {
  theme: {
    colors: {
      transparent: 'transparent',
      black: {
        500: '#22292f',
      },
      white: '#fff',
      grey: {
        100: '#f7fafc',
        200: '#edf2f7',
        300: '#e2e8f0',
        400: '#cbd5e0',
        500: '#a0aec0',
        600: '#718096',
        700: '#4a5568',
        800: '#2d3748',
        900: '#1a202c',
      },
      red: {
        500: '#f56565',
        600: '#e53e3e',
        700: '#c53030',
      },
      yellow: {
        500: '#ecc94b',
        600: '#d69e2e',
        700: '#b7791f',
      },
      green: {
        500: '#48bb78',
        600: '#38a169',
        700: '#2f855a',
      },
      blue: {
        200: '#bee3f8',
        500: '#4299e1',
        600: '#3182ce',
        700: '#2b6cb0',
        800: '#2c5282',
        900: '#2a4365',
      },
    },
  },
  variants: {
    appearance: [],
    backgroundAttachment: [],
    backgroundPosition: ['responsive'],
    backgroundRepeat: ['responsive'],
    backgroundSize: ['responsive'],
    borderCollapse: [],
    borderRadius: [],
    borderStyle: ['responsive'],
    borderWidths: ['responsive'],
    cursor: [],
    display: ['responsive'],
    flexbox: ['responsive'],
    fontWeights: [],
    height: ['responsive'],
    leading: [],
    lists: [],
    margin: ['responsive'],
    maxHeight: ['responsive'],
    maxWidth: ['responsive'],
    minHeight: ['responsive'],
    minWidth: ['responsive'],
    negativeMargin: ['responsive'],
    opacity: [],
    outline: ['focus'],
    overflow: ['responsive'],
    padding: ['responsive'],
    position: ['responsive'],
    textAlign: ['responsive'],
    textSizes: ['responsive'],
    verticalAlign: ['responsive'],
    whitespace: ['responsive'],
    width: ['responsive'],
    zIndex: ['responsive'],
  },
  plugins: [],
  corePlugins: {
    appearance: false,
    fonts: false,
    pointerEvents: false,
    resize: false,
    svgFill: false,
    svgStroke: false,
    tracking: false,
    userSelect: false,
    visibility: false,
  },
};
